# Numpy

In [2]:
import numpy as np
import sys

!python -V
print(sys.executable)

Python 3.9.6
C:\Users\HAL9000\anaconda3\envs\data_science\python.exe


## Arrays, Linspace

**Remarks**
- arr.copy()  ...parts of array overwritten! --> Copy array
- functions:  
  - dtype
  - max
  - argmin
- Indexing
- Selections

### Types

In [3]:
lst = [1, 2, 3]
np.array(lst)

array([1, 2, 3])

In [4]:
matrix = [[1, 2, 3], [4, 5, 6]]
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
# Functions

np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [7]:
np.zeros(3)

array([0., 0., 0.])

In [8]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
np.linspace(0, 1)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [11]:
np.random.randn(10)

array([ 2.20090899,  0.12085016,  1.52468564, -0.49315311,  0.14900796,
        0.04411506,  1.53873537, -1.32805901, -0.00769842, -0.86060552])

### Array functions

In [12]:
arr = np.arange(25)
ranarr =np.random.randint(0, 50, 10)

arrMatrix = arr.reshape(5,5)

# Maximum of array and position of Max
ranarr.max()
ranarr.argmin()

# Shape of array
arrMatrix.shape

# Type of array
arr.dtype

dtype('int32')

### Indexing

In [13]:
arr2 = np.arange(0, 11)

arr2[2:4]

array([2, 3])

In [14]:
# ATTENTION! Array will be overwritten!!

arr2Part = arr2[0:6]
arr2Part[:] = 12 

print(arr2Part)
print(arr2)

arr2Copy = arr2.copy()
arr2Copy[:] = 99

print(arr2Copy)
print(arr2)

[12 12 12 12 12 12]
[12 12 12 12 12 12  6  7  8  9 10]
[99 99 99 99 99 99 99 99 99 99 99]
[12 12 12 12 12 12  6  7  8  9 10]


In [15]:
# 2D Array

arr2d = np.array(([5, 10, 15], [20, 25, 30], [35, 40, 45]))
arr2d[1][0]
arr2d[1, 0]
arr2d[1:]  # 2. and 3. row
arr2d[:2,1:]  #  1. and 2. row, 2. and 3. column 

# exercise: 
arrEx = np.arange(50).reshape(5, 10)
arrEx

# get 13, 14 and 24, 24
arrEx[1:3, 3:5]

array([[13, 14],
       [23, 24]])

### Selection

In [16]:
# Create array and use boolean operation on it

arr3 = np.arange(0, 11, 1)
arr3bool = arr3 < 5
arr3bool

# use bool-array on original array!

arr3[arr3bool]
arr3[arr3>6]

array([ 7,  8,  9, 10])

## NumPy Operations

 [universelle Array Funktionen](http://docs.scipy.org/doc/numpy/reference/ufuncs.html)

In [19]:
arr = np.arange(0, 10)
arr + arr
arr*3
np.sqrt(arr)
np.exp(arr)
np.sin(arr)
np.log(arr)
print(arr)

arr / arr
1 / arr

[0 1 2 3 4 5 6 7 8 9]


<ipython-input-19-5f0c600045d1>:7: RuntimeWarning: divide by zero encountered in log
  np.log(arr)
<ipython-input-19-5f0c600045d1>:10: RuntimeWarning: invalid value encountered in true_divide
  arr / arr
<ipython-input-19-5f0c600045d1>:11: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])