# Numpy

In [18]:
import numpy as np
import sys

!python -V
print(sys.executable)

Python 3.10.4
C:\repos\Python-Data-Science\venv\Scripts\python.exe


In [19]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

## Arrays, Linspace

**Remarks**
- arr.copy()  ...parts of array overwritten! --> Copy array
- functions:  
  - dtype
  - max
  - argmin
- Indexing
- Selections

### Types

In [20]:
lst = [1, 2, 3]
np.array(lst)

array([1, 2, 3])

In [21]:
matrix = [[1, 2, 3], [4, 5, 6]]
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
# Functions

np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [24]:
np.zeros(3)

array([0., 0., 0.])

In [25]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [26]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
np.linspace(0, 1)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [28]:
np.random.randn(10)

array([-0.36113731, -0.04443472,  0.07008011, -0.19276119, -0.36258549,
        0.8451997 ,  1.38063543,  0.81686078, -1.02318354, -0.95740581])

### Array functions

In [29]:
arr = np.arange(25)
ranarr =np.random.randint(0, 50, 10)
ranarr

arrMatrix = arr.reshape(5,5)

# Maximum of array and position of Max
ranarr.max()
ranarr.argmin()

# Shape of array
arrMatrix.shape

# Type of array
arr.dtype



array([10, 15, 22, 27, 20, 44, 13, 13, 48, 15])

48

0

(5, 5)

dtype('int32')

### Indexing

In [39]:
arr2 = np.arange(0, 11)
arr2
arr2[2:4]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

array([2, 3])

In [40]:
# ATTENTION! Array will be overwritten!!

arr2Part = arr2[0:6]
arr2Part[:] = 12 

print(arr2Part)
print(arr2)

arr2Copy = arr2.copy()
arr2Copy[:] = 99

print(arr2Copy)
print(arr2)

[12 12 12 12 12 12]
[12 12 12 12 12 12  6  7  8  9 10]
[99 99 99 99 99 99 99 99 99 99 99]
[12 12 12 12 12 12  6  7  8  9 10]


In [41]:
# 2D Array

arr2d = np.array(([5, 10, 15], [20, 25, 30], [35, 40, 45]))
arr2d
arr2d[1][0]
arr2d[1, 0]
arr2d[1:]  # 2. and 3. row - alles ab erster zeile
arr2d[:2,1:]  #  1. and 2. row, 2. and 3. column - alles bis 2ter zeile und ab 1. spalte

# exercise: 
arrEx = np.arange(50).reshape(5, 10)
arrEx

# get 13, 14 and 24, 24
arrEx[1:3, 3:5]

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

20

20

array([[20, 25, 30],
       [35, 40, 45]])

array([[10, 15],
       [25, 30]])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

array([[13, 14],
       [23, 24]])

### Selection

In [33]:
# Create array and use boolean operation on it

arr3 = np.arange(0, 11, 1)
arr3bool = arr3 < 5
arr3bool

# use bool-array on original array!

arr3[arr3bool]
arr3[arr3>6]

array([ True,  True,  True,  True,  True, False, False, False, False,
       False, False])

array([0, 1, 2, 3, 4])

array([ 7,  8,  9, 10])

## NumPy Operations

 [universelle Array Funktionen](http://docs.scipy.org/doc/numpy/reference/ufuncs.html)

In [34]:
arr = np.arange(0, 10)
arr
arr + arr
arr*3
np.sqrt(arr)
np.exp(arr)
np.sin(arr)
np.log(arr)
print(arr)

arr / arr
1 / arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

C:\Users\das_m\AppData\Local\Temp\ipykernel_13416\2149909887.py:8: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

[0 1 2 3 4 5 6 7 8 9]


C:\Users\das_m\AppData\Local\Temp\ipykernel_13416\2149909887.py:11: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

C:\Users\das_m\AppData\Local\Temp\ipykernel_13416\2149909887.py:12: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])